name: Web CI

on:
  push:
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    paths:
      - 'web/**'
      - '.github/workflows/web-ci.yml'

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun run lint

      - name: Run TypeScript type-check
        run: bun run typecheck
